// src/components/recommendations/data/sampleRecommendations.js
export const getSampleRecommendations = (t) => ({
  streams: [
    {
      _id: "1",
      name: t("recommendations_1.sampleData.streams.science.name"),
      description: t("recommendations_1.sampleData.streams.science.description"),
      matchScore: 85,
      category: t("recommendations_1.sampleData.streams.science.category"),
    },
    {
      _id: "2",
      name: t("recommendations_1.sampleData.streams.commerce.name"),
      description: t("recommendations_1.sampleData.streams.commerce.description"),
      matchScore: 75,
      category: t("recommendations_1.sampleData.streams.commerce.category"),
    },
    {
      _id: "3",
      name: t("recommendations_1.sampleData.streams.arts.name"),
      description: t("recommendations_1.sampleData.streams.arts.description"),
      matchScore: 70,
      category: t("recommendations_1.sampleData.streams.arts.category"),
    },
    {
      _id: "4",
      name: t("recommendations_1.sampleData.streams.vocational.name"),
      description: t("recommendations_1.sampleData.streams.vocational.description"),
      matchScore: 65,
      category: t("recommendations_1.sampleData.streams.vocational.category"),
    },
    {
      _id: "5",
      name: t("recommendations_1.sampleData.streams.law.name"),
      description: t("recommendations_1.sampleData.streams.law.description"),
      matchScore: 72,
      category: t("recommendations_1.sampleData.streams.law.category"),
    },
    {
      _id: "6",
      name: t("recommendations_1.sampleData.streams.medical.name"),
      description: t("recommendations_1.sampleData.streams.medical.description"),
      matchScore: 88,
      category: t("recommendations_1.sampleData.streams.medical.category"),
    },
    {
      _id: "7",
      name: t("recommendations_1.sampleData.streams.fineArts.name"),
      description: t("recommendations_1.sampleData.streams.fineArts.description"),
      matchScore: 60,
      category: t("recommendations_1.sampleData.streams.fineArts.category"),
    },
    {
      _id: "8",
      name: t("recommendations_1.sampleData.streams.agriculture.name"),
      description: t("recommendations_1.sampleData.streams.agriculture.description"),
      matchScore: 68,
      category: t("recommendations_1.sampleData.streams.agriculture.category"),
    },
  ],

  degrees: [
    {
      _id: "1",
      name: t("recommendations_1.sampleData.degrees.btech.name"),
      description: t("recommendations_1.sampleData.degrees.btech.description"),
      level: t("recommendations_1.sampleData.degrees.btech.level"),
      matchScore: 90,
      duration: "4 years",
      averageFee: 200000,
    },
    {
      _id: "2",
      name: t("recommendations_1.sampleData.degrees.bcom.name"),
      description: t("recommendations_1.sampleData.degrees.bcom.description"),
      level: t("recommendations_1.sampleData.degrees.bcom.level"),
      matchScore: 80,
      duration: "3 years",
      averageFee: 120000,
    },
    {
      _id: "3",
      name: t("recommendations_1.sampleData.degrees.ba.name"),
      description: t("recommendations_1.sampleData.degrees.ba.description"),
      level: t("recommendations_1.sampleData.degrees.ba.level"),
      matchScore: 75,
      duration: "3 years",
      averageFee: 100000,
    },
    {
      _id: "4",
      name: t("recommendations_1.sampleData.degrees.bsc.name"),
      description: t("recommendations_1.sampleData.degrees.bsc.description"),
      level: t("recommendations_1.sampleData.degrees.bsc.level"),
      matchScore: 78,
      duration: "3 years",
      averageFee: 150000,
    },
    {
      _id: "5",
      name: t("recommendations_1.sampleData.degrees.mbbs.name"),
      description: t("recommendations_1.sampleData.degrees.mbbs.description"),
      level: t("recommendations_1.sampleData.degrees.mbbs.level"),
      matchScore: 92,
      duration: "5.5 years",
      averageFee: 600000,
    },
    {
      _id: "6",
      name: t("recommendations_1.sampleData.degrees.bfa.name"),
      description: t("recommendations_1.sampleData.degrees.bfa.description"),
      level: t("recommendations_1.sampleData.degrees.bfa.level"),
      matchScore: 70,
      duration: "4 years",
      averageFee: 180000,
    },
    {
      _id: "7",
      name: t("recommendations_1.sampleData.degrees.llb.name"),
      description: t("recommendations_1.sampleData.degrees.llb.description"),
      level: t("recommendations_1.sampleData.degrees.llb.level"),
      matchScore: 82,
      duration: "3 years",
      averageFee: 220000,
    },
    {
      _id: "8",
      name: t("recommendations_1.sampleData.degrees.bba.name"),
      description: t("recommendations_1.sampleData.degrees.bba.description"),
      level: t("recommendations_1.sampleData.degrees.bba.level"),
      matchScore: 85,
      duration: "3 years",
      averageFee: 250000,
    },
  ],

  colleges: [
    {
      _id: "1",
      name: t("recommendations_1.sampleData.colleges.iitDelhi.name"),
      type: t("recommendations_1.sampleData.colleges.iitDelhi.type"),
      location: t("recommendations_1.sampleData.colleges.iitDelhi.location"),
      rating: 4.8,
      studentsCount: 8000,
      averageFee: 200000,
    },
    {
      _id: "2",
      name: t("recommendations_1.sampleData.colleges.delhiUniversity.name"),
      type: t("recommendations_1.sampleData.colleges.delhiUniversity.type"),
      location: t("recommendations_1.sampleData.colleges.delhiUniversity.location"),
      rating: 4.6,
      studentsCount: 200000,
      averageFee: 60000,
    },
    {
      _id: "3",
      name: t("recommendations_1.sampleData.colleges.christUniversity.name"),
      type: t("recommendations_1.sampleData.colleges.christUniversity.type"),
      location: t("recommendations_1.sampleData.colleges.christUniversity.location"),
      rating: 4.4,
      studentsCount: 25000,
      averageFee: 180000,
    },
    {
      _id: "4",
      name: t("recommendations_1.sampleData.colleges.stXaviers.name"),
      type: t("recommendations_1.sampleData.colleges.stXaviers.type"),
      location: t("recommendations_1.sampleData.colleges.stXaviers.location"),
      rating: 4.5,
      studentsCount: 5000,
      averageFee: 120000,
    },
    {
      _id: "5",
      name: t("recommendations_1.sampleData.colleges.aiims.name"),
      type: t("recommendations_1.sampleData.colleges.aiims.type"),
      location: t("recommendations_1.sampleData.colleges.aiims.location"),
      rating: 4.9,
      studentsCount: 15000,
      averageFee: 300000,
    },
    {
      _id: "6",
      name: t("recommendations_1.sampleData.colleges.nlsiu.name"),
      type: t("recommendations_1.sampleData.colleges.nlsiu.type"),
      location: t("recommendations_1.sampleData.colleges.nlsiu.location"),
      rating: 4.7,
      studentsCount: 2000,
      averageFee: 250000,
    },
    {
      _id: "7",
      name: t("recommendations_1.sampleData.colleges.bhu.name"),
      type: t("recommendations_1.sampleData.colleges.bhu.type"),
      location: t("recommendations_1.sampleData.colleges.bhu.location"),
      rating: 4.6,
      studentsCount: 30000,
      averageFee: 100000,
    },
    {
      _id: "8",
      name: t("recommendations_1.sampleData.colleges.symbiosis.name"),
      type: t("recommendations_1.sampleData.colleges.symbiosis.type"),
      location: t("recommendations_1.sampleData.colleges.symbiosis.location"),
      rating: 4.3,
      studentsCount: 18000,
      averageFee: 200000,
    },
  ],

  careers: [
    {
      _id: "1",
      title: t("recommendations_1.sampleData.careers.softwareEngineer.title"),
      description: t("recommendations_1.sampleData.careers.softwareEngineer.description"),
      industry: t("recommendations_1.sampleData.careers.softwareEngineer.industry"),
      matchScore: 88,
      averageSalary: 800000,
      growthRate: t("recommendations_1.sampleData.careers.softwareEngineer.growthRate"),
    },
    {
      _id: "2",
      title: t("recommendations_1.sampleData.careers.charteredAccountant.title"),
      description: t("recommendations_1.sampleData.careers.charteredAccountant.description"),
      industry: t("recommendations_1.sampleData.careers.charteredAccountant.industry"),
      matchScore: 82,
      averageSalary: 900000,
      growthRate: t("recommendations_1.sampleData.careers.charteredAccountant.growthRate"),
    },
    {
      _id: "3",
      title: t("recommendations_1.sampleData.careers.civilServicesOfficer.title"),
      description: t("recommendations_1.sampleData.careers.civilServicesOfficer.description"),
      industry: t("recommendations_1.sampleData.careers.civilServicesOfficer.industry"),
      matchScore: 78,
      averageSalary: 700000,
      growthRate: t("recommendations_1.sampleData.careers.civilServicesOfficer.growthRate"),
    },
    {
      _id: "4",
      title: t("recommendations_1.sampleData.careers.graphicDesigner.title"),
      description: t("recommendations_1.sampleData.careers.graphicDesigner.description"),
      industry: t("recommendations_1.sampleData.careers.graphicDesigner.industry"),
      matchScore: 72,
      averageSalary: 400000,
      growthRate: t("recommendations_1.sampleData.careers.graphicDesigner.growthRate"),
    },
    {
      _id: "5",
      title: t("recommendations_1.sampleData.careers.doctor.title"),
      description: t("recommendations_1.sampleData.careers.doctor.description"),
      industry: t("recommendations_1.sampleData.careers.doctor.industry"),
      matchScore: 92,
      averageSalary: 1200000,
      growthRate: t("recommendations_1.sampleData.careers.doctor.growthRate"),
    },
    {
      _id: "6",
      title: t("recommendations_1.sampleData.careers.lawyer.title"),
      description: t("recommendations_1.sampleData.careers.lawyer.description"),
      industry: t("recommendations_1.sampleData.careers.lawyer.industry"),
      matchScore: 80,
      averageSalary: 1000000,
      growthRate: t("recommendations_1.sampleData.careers.lawyer.growthRate"),
    },
    {
      _id: "7",
      title: t("recommendations_1.sampleData.careers.entrepreneur.title"),
      description: t("recommendations_1.sampleData.careers.entrepreneur.description"),
      industry: t("recommendations_1.sampleData.careers.entrepreneur.industry"),
      matchScore: 76,
      averageSalary: 1500000,
      growthRate: t("recommendations_1.sampleData.careers.entrepreneur.growthRate"),
    },
    {
      _id: "8",
      title: t("recommendations_1.sampleData.careers.dataScientist.title"),
      description: t("recommendations_1.sampleData.careers.dataScientist.description"),
      industry: t("recommendations_1.sampleData.careers.dataScientist.industry"),
      matchScore: 89,
      averageSalary: 1400000,
      growthRate: t("recommendations_1.sampleData.careers.dataScientist.growthRate"),
    },
  ],

  content: [
    {
      _id: "1",
      title: t("recommendations_1.sampleData.content.jeeGuide.title"),
      description: t("recommendations_1.sampleData.content.jeeGuide.description"),
      type: t("recommendations_1.sampleData.content.jeeGuide.type"),
      rating: 4.5,
      duration: "2 hours",
      enrollments: 1500,
    },
    {
      _id: "2",
      title: t("recommendations_1.sampleData.content.commercePack.title"),
      description: t("recommendations_1.sampleData.content.commercePack.description"),
      type: t("recommendations_1.sampleData.content.commercePack.type"),
      rating: 4.2,
      duration: "3 hours",
      enrollments: 1200,
    },
    {
      _id: "3",
      title: t("recommendations_1.sampleData.content.upscGuide.title"),
      description: t("recommendations_1.sampleData.content.upscGuide.description"),
      type: t("recommendations_1.sampleData.content.upscGuide.type"),
      rating: 4.6,
      duration: "5 hours",
      enrollments: 2500,
    },
    {
      _id: "4",
      title: t("recommendations_1.sampleData.content.graphicDesignCourse.title"),
      description: t("recommendations_1.sampleData.content.graphicDesignCourse.description"),
      type: t("recommendations_1.sampleData.content.graphicDesignCourse.type"),
      rating: 4.3,
      duration: "6 hours",
      enrollments: 3000,
    },
    {
      _id: "5",
      title: t("recommendations_1.sampleData.content.neetCourse.title"),
      description: t("recommendations_1.sampleData.content.neetCourse.description"),
      type: t("recommendations_1.sampleData.content.neetCourse.type"),
      rating: 4.7,
      duration: "10 hours",
      enrollments: 3500,
    },
    {
      _id: "6",
      title: t("recommendations_1.sampleData.content.corporateLaw.title"),
      description: t("recommendations_1.sampleData.content.corporateLaw.description"),
      type: t("recommendations_1.sampleData.content.corporateLaw.type"),
      rating: 4.1,
      duration: "4 hours",
      enrollments: 1000,
    },
    {
      _id: "7",
      title: t("recommendations_1.sampleData.content.entrepreneurshipMaster.title"),
      description: t("recommendations_1.sampleData.content.entrepreneurshipMaster.description"),
      type: t("recommendations_1.sampleData.content.entrepreneurshipMaster.type"),
      rating: 4.8,
      duration: "3 hours",
      enrollments: 4000,
    },
    {
      _id: "8",
      title: t("recommendations_1.sampleData.content.dataScienceBootcamp.title"),
      description: t("recommendations_1.sampleData.content.dataScienceBootcamp.description"),
      type: t("recommendations_1.sampleData.content.dataScienceBootcamp.type"),
      rating: 4.9,
      duration: "15 hours",
      enrollments: 5000,
    },
  ],
});
